<a href="https://colab.research.google.com/github/RiazullJannat/DL/blob/main/pytorch_traning_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [34]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [35]:
df.shape

(569, 33)

In [36]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [37]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [38]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [39]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [40]:
X_train

array([[ 2.15061071, -0.45553713,  2.01249073, ...,  1.07542085,
        -0.63733318, -1.08711683],
       [-0.67195777,  1.23735167, -0.62177788, ...,  0.279374  ,
        -0.17190592,  0.90632814],
       [-0.56491426, -1.35260337, -0.5621772 , ..., -0.60482882,
        -0.20685268, -0.19362222],
       ...,
       [ 2.16187845,  0.42504759,  2.273754  , ...,  1.10807121,
        -0.12425125,  0.26860927],
       [ 1.3928553 ,  1.27266924,  1.24094762, ...,  1.28687079,
         1.6596218 ,  0.51520919],
       [ 0.46608381, -1.86117636,  0.4571578 , ...,  0.50326218,
        -0.5626742 , -0.11964224]])

In [41]:
y_train

368    M
537    B
529    B
360    B
250    M
      ..
470    B
548    B
272    M
87     M
484    B
Name: diagnosis, Length: 455, dtype: object

In [42]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [43]:
y_train

array([1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0])

In [44]:
type(X_train)

numpy.ndarray

In [45]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [46]:
X_train_tensor.shape

torch.Size([455, 30])

In [47]:
y_train_tensor.shape

torch.Size([455])

# Defining the model

In [48]:
class MySimpleNN():

  def __init__(self, X):
    self.weights = torch.rand(X.shape[1],1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias

    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    #clamp predicitons to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log( 1 - y_pred)).mean()
    return loss

# Importnat Paramenters

In [49]:
learning_rate = 0.1
epochs = 45

In [50]:
#create moddel

model = MySimpleNN(X_train_tensor)

#define loop
for epoch in range(epochs):
  #forward pass
  y_pred = model.forward(X_train_tensor)

  #loss calculate
  loss = model.loss_function(y_pred, y_test_tensor)

  #backward pass
  loss.backward()


  #parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f"epoch: {epoch + 1}, Loss: {loss.item()}")

epoch: 1, Loss: 3.3278549447301407
epoch: 2, Loss: 3.195269145866013
epoch: 3, Loss: 3.056152363662794
epoch: 4, Loss: 2.914057568582156
epoch: 5, Loss: 2.7681837310923703
epoch: 6, Loss: 2.6181857855844055
epoch: 7, Loss: 2.4623675073427003
epoch: 8, Loss: 2.3009260979766832
epoch: 9, Loss: 2.139307051994546
epoch: 10, Loss: 1.980965202446092
epoch: 11, Loss: 1.8278246356826053
epoch: 12, Loss: 1.6765853373378516
epoch: 13, Loss: 1.5360977398776046
epoch: 14, Loss: 1.4082485941498348
epoch: 15, Loss: 1.292849064030761
epoch: 16, Loss: 1.191336673601756
epoch: 17, Loss: 1.1065206842825612
epoch: 18, Loss: 1.0363869837935387
epoch: 19, Loss: 0.975367780053239
epoch: 20, Loss: 0.9278282828647327
epoch: 21, Loss: 0.8913372798835093
epoch: 22, Loss: 0.8634795450265869
epoch: 23, Loss: 0.8420661512209872
epoch: 24, Loss: 0.8252754723294979
epoch: 25, Loss: 0.8117077013599268
epoch: 26, Loss: 0.8003604555812147
epoch: 27, Loss: 0.7905558976616424
epoch: 28, Loss: 0.7818542206507335
epoch: 29, Loss: 0.7739769695530596
epoch: 30, Loss: 0.7667491290611149
epoch: 31, Loss: 0.7600595024218957
epoch: 32, Loss: 0.7538352786134547
epoch: 33, Loss: 0.7480263849957006
epoch: 34, Loss: 0.7425961388124462
epoch: 35, Loss: 0.7375157798293334
epoch: 36, Loss: 0.7327613246158763
epoch: 37, Loss: 0.728311779945671
epoch: 38, Loss: 0.7241481383950692
epoch: 39, Loss: 0.72025281759069
epoch: 40, Loss: 0.7166093477131281
epoch: 41, Loss: 0.7132021960651442
epoch: 42, Loss: 0.7100166662274718
epoch: 43, Loss: 0.7070388371129114
epoch: 44, Loss: 0.704255522874607
epoch: 45, Loss: 0.7016542433247523

In [51]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5789473652839661